name: Tests

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Ejecutar pruebas

    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.18.0
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar tests con cobertura
        run: npm run test:coverage
